import { useEffect, useState } from 'react'
import './App.css'

const img = (id: string) => `https://images.unsplash.com/${id}?auto=format&fit=crop&w=1600&q=82`
const I = {
  counter: img('photo-1556745757-8d76bdb6984b'),
  service: img('photo-1556742031-c6961e8560b0'),
  headshot: img('photo-1494790108377-be9c29b29330'),
  family: img('photo-1511895426328-dc8714191300'),
  studio: img('photo-1500648767791-00dcc994a43e'),
  owner: img('photo-1551836022-d5d88e9218df'),
  business: img('photo-1556761175-b413da4baf72'),
  job: img('photo-1573496359142-b8d87734a5a2'),
  marketing: img('photo-1460925895917-afdab827c52f'),
  location: img('photo-1517245386807-bb43f82c33c4'),
}

const pillars = [
  ['01','photoshoot','AI Virtual Photoshoot','Headshots, families, matric dance, products and school shoots.','R150–R900'],
  ['02','job-seeker','AI Job Seeker','CV redesign, cover letters, LinkedIn and interview prep.','R75–R600'],
  ['03','small-business','AI Small Business','Logos, cards, flyers, WhatsApp and Google profile setup.','R150–R1,800'],
  ['04','advisors','AI Advisors & Coaches','Business, career, marketing, sales and study coaching.','R200–R350'],
  ['05','marketing','AI Marketing & Content','Monthly posts, captions, campaigns and local promotion packs.','R750/mo'],
  ['06','websites','AI Websites & Digital','Landing pages, eight-page websites and Google optimisation.','R450–R3,500'],
  ['07','calculators','AI Calculators & Dashboards','Pricing, ROI, profit, break-even and owner dashboards.','R50–R350/mo'],
  ['08','documents','AI Documents & Profiles','Profiles, tender docs, letters, affidavits and contracts.','R100–R750'],
]
const services = ['Vehicle Licence Renewal','Courier (Local)','Courier (International)','Printing & Copying','Photo & ID Services','Photo Printing','Key Cutting','Crime Checks','Credit Checks','Lamination & Binding','Scanning & Email','Document Services','AI Photoshoot','AI Job Seeker Pack','AI Small Business Starter','AI Company Profile','AI Marketing Pack']
const bundles = [
  ['Job Seeker Pack','R800',I.job,'CV + cover letter + LinkedIn + AI headshot + 10 printed CVs + interview booklet'],
  ['Small Business Starter','R1,800',I.business,'Logo + 250 business cards + 100 flyers + WhatsApp Business + Google profile + QR code'],
  ['New Business Pack','R4,500',I.service,'Name registration + CIPC + logo + business plan + 8-page website + first social posts'],
]
const photoRows = ['LinkedIn Headshot|One polished profile photo, digital file and print-ready crop|R150','Professional Headshot Plus|Four variations: corporate, warm, studio, monochrome|R250','Executive Pack|Eight executive portraits with retouching and usage crops|R450','Family Portrait Mini|Three AI-assisted family portraits from one in-store session|R250','Family Portrait Full|Ten portraits, digital gallery and two printed photos|R650','Matric Dance Portrait|Styled single portrait and social-ready gallery crops|R350','Matric Dance Couple|Couple set, cinematic portraits and print-ready keepsake|R600','Maternity Portrait|Soft studio-inspired maternity set, six finished images|R450','Baby Milestone|Six baby milestone portraits with print-ready files|R350','Brand Founder Shoot|Founder portraits for WhatsApp, LinkedIn and flyers|R550','Product Mini|Five clean product shots for WhatsApp catalogue listings|R300','Product Full|Fifteen product shots with cleanup and captions|R900','Church Leader Portrait|Formal portrait pack for programmes and announcements|R250','Sports Club Pack|Player portrait with team-colour treatment and print file|R200','School Learner Pack|Learner portrait, certificate crop and parent-order file|R350','Bulk Event Pack|Priced per brief for schools, churches and club days|Quote'].map(x=>x.split('|'))

const BASE = import.meta.env.BASE_URL.replace(/\/$/,'')
const stripBase = (pathname:string) => BASE && pathname === BASE ? '/' : BASE && pathname.startsWith(`${BASE}/`) ? pathname.slice(BASE.length) || '/' : pathname
const withBase = (route:string) => BASE ? `${BASE}${route}` : route
function App(){
  const [path,setPath]=useState(stripBase(location.pathname))
  const [hide,setHide]=useState(false)
  const [mega,setMega]=useState(false)
  useEffect(()=>{const p=()=>setPath(stripBase(location.pathname)); addEventListener('popstate',p); return()=>removeEventListener('popstate',p)},[])
  useEffect(()=>{let last=scrollY; const s=()=>{setHide(scrollY>120&&scrollY>last); last=scrollY}; addEventListener('scroll',s,{passive:true}); return()=>removeEventListener('scroll',s)},[])
  useEffect(()=>{const c=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a') as HTMLAnchorElement|null; if(!a)return; const u=new URL(a.href); if(u.origin!==location.origin)return; const route=stripBase(u.pathname); e.preventDefault(); history.pushState({},'',withBase(route)); setPath(route); setMega(false); scrollTo({top:0,behavior:'smooth'})}; document.addEventListener('click',c); return()=>document.removeEventListener('click',c)},[])
  return <><Header hide={hide} mega={mega} setMega={setMega}/><main>{page(path)}</main><Footer/><a className="wa-float" href="https://wa.me/27XXXXXXXXX?text=Hi%20Post%40WEB%2C%20I'd%20like%20to%20know%20more%20about...">+27<br/>XX</a></>
}
function Header({hide,mega,setMega}:{hide:boolean;mega:boolean;setMega:(v:boolean)=>void}){
  return <header className={`site-nav ${hide?'is-hidden':''}`} onMouseLeave={()=>setMega(false)}><div className="nav-shell"><a className="wordmark" href="/"><span>POST</span><b>@WEB</b></a><nav className="nav-links"><a href="/services">Services</a><button onMouseEnter={()=>setMega(true)}>AI Help Desk</button><a href="/bundles">Bundles</a><a href="/locations">Locations</a><a href="/about">About</a></nav><div className="nav-actions"><a className="find" href="/locations">Find a Store</a><a className="btn primary" href="/contact">Talk to us</a></div></div><div className={`mega ${mega?'open':''}`}><div className="mega-list">{pillars.map(p=><a key={p[1]} href={`/ai-help-desk/${p[1]}`}><span>{p[0]}</span>{p[2]}</a>)}</div><div className="mega-detail"><p className="kicker">ACTIVE COUNTER CATEGORY</p><h3>Eight walk-in AI pillars</h3><p>Real deliverables with real Rand prices, sold at the Post@WEB counter.</p></div><div className="mega-offer"><p className="kicker">FEATURED OFFER</p><h3>Small Business Starter</h3><strong>R1,800</strong><p>Logo, cards, flyers, WhatsApp, Google profile and QR code.</p><a href="/bundles">Book this pack →</a></div></div></header>
}
function page(path:string){
  if(path==='/')return <Home/>; if(path==='/services')return <Services/>; if(path==='/ai-help-desk')return <Ai/>; if(path==='/ai-help-desk/photoshoot')return <Photoshoot/>; if(path.startsWith('/ai-help-desk/'))return <Pillar/>; if(path==='/bundles')return <Bundles/>; if(path==='/for-business')return <ForBusiness/>; if(path==='/locations')return <Locations/>; if(path==='/franchise')return <Franchise/>; if(path==='/about')return <About/>; if(path==='/contact')return <Contact/>; return <PageHero eyebrow="POST@WEB" title="This counter is not open yet."/>
}
function Marker({n,e}:{n:string;e:string}){return <div className="section-marker"><span>{n}</span><p className="kicker">{e}</p></div>}
function Home(){return <><section className="home-hero dark"><div className="hero-copy"><p className="kicker">POST@WEB · ESTABLISHED IN MALLS NATIONWIDE</p><h1>Walk in with a problem.<br/>Walk out with the <em>answer.</em></h1><p className="lede">Licence renewal, courier, printing, photo services — and the country's first walk-in AI Help Desk. All under one red roof.</p><div className="button-row"><a className="btn primary" href="/locations">Find your nearest store</a><a className="btn ghost light" href="/services">Explore services</a></div><div className="partners"><span/>PARTNERED WITH · The Courier Guy · FedEx · Kodak</div></div><figure className="hero-photo"><img src={I.counter} alt="Retail service counter"/></figure></section><section className="section"><Marker n="01" e="WHAT WE DO"/><h2>Everything you walked in for. And a lot you didn't know to ask for.</h2><div className="service-grid">{services.map((s,i)=><a className="service-cell" href="/services" key={s}><strong>{s}</strong><span>{i<12?'Everyday admin handled with counter speed.':'A finished AI-powered deliverable, not a software lesson.'}</span></a>)}</div><a className="oversize-link" href="/services">See all 80+ services →</a></section><section className="ai-intro dark"><div><p className="kicker">INTRODUCING · NEW IN 2026</p><h2>The AI Help Desk.</h2><p className="lede">CVs. Headshots. Logos. Websites. Business plans. Eight categories, eighty plus services. Done at the counter. Delivered the same day.</p><a className="btn primary" href="/ai-help-desk">Walk through the catalogue →</a></div><div className="pillar-lines">{pillars.map(p=><a href={`/ai-help-desk/${p[1]}`} key={p[1]}><b>{p[0]}</b><span><strong>{p[2]}</strong>{p[3]}</span></a>)}</div></section><BundlesTeaser/><Journey/><LocationsTeaser/><section className="split-cta"><div className="dark"><p className="kicker">FRANCHISE OPPORTUNITY</p><h2>Run your own Post@WEB.</h2><p>Own a counter-led retail service brand with national service partners and a new AI line.</p><a href="/franchise">Find out more →</a></div><div className="red"><p className="kicker white">BECOME A B2B PARTNER</p><h2>R105,000 from one Saturday.</h2><p>300 learners at R350 each turns one school photo day into serious revenue.</p><a href="/for-business">Talk to our B2B team →</a></div></section><PreFooter/></>}
function BundlesTeaser(){return <section className="section bundles-strip"><Marker n="02" e="BUNDLES · NAMED OUTCOMES"/><h2>Three outcomes. Three prices. Three counter cards.</h2><div className="home-bundle-cards">{bundles.map((b,i)=><article className={`bundle-mini ${i===1?'hero-card':''}`} key={b[0]}><h3>{b[0]}</h3><strong>{b[1]}</strong><ul>{String(b[3]).split(' + ').slice(0,5).map(x=><li key={x}>{x}</li>)}</ul><a href="/bundles">Book this pack →</a></article>)}</div></section>}
function Journey(){return <section className="section journey"><Marker n="03" e="IN PRACTICE"/><h2>What it looks like when Thandi walks in.</h2><div className="journey-row">{['The walk-in','The upsell','The brief','The result'].map((t,i)=><article className="journey-block" key={t}>{i!==1&&<img src={[I.owner,I.business,I.marketing][i>1?i-1:i]} alt="customer"/>}<div><h3>{i+1} · {t}</h3><p>{['Thandi runs a home salon. She came in to print 100 flyers.','Our team showed her the Small Business Starter Pack for R1,800.','She spent 12 minutes at the counter and showed us photos on her phone.','Three days later she opened with a brand and six WhatsApp bookings.'][i]}</p></div></article>)}</div></section>}
function LocationsTeaser(){return <section className="locations-preview dark"><div><p className="kicker">WHERE TO FIND US</p><h2>Two stores. National rollout in progress.</h2><p className="lede">Rosebank and Dobsonville prove the model: mall convenience, trusted admin services and AI-powered finished work.</p></div><div className="location-stack"><Card t="Post@WEB Rosebank"/><Card t="Post@WEB Dobsonville"/></div></section>}
function Card({t}:{t:string}){return <article className="location-card"><h3>{t}</h3><p>Mon–Sat · Mall trading hours<br/>+27 XX XXX XXXX</p><a href="/locations">Get directions →</a></article>}
function PreFooter(){return <section className="prefooter"><h2>Have a question, or need it done fast?</h2><div><a href="/contact">WhatsApp us</a><span>·</span><a href="/contact">Call us</a><span>·</span><a href="/locations">Find a store</a></div></section>}
function PageHero({eyebrow,title}:{eyebrow:string;title:string}){return <section className="page-hero"><p className="kicker">{eyebrow}</p><h1>{title}</h1></section>}
function HeroDark({eyebrow,title}:{eyebrow:string;title:string}){return <section className="hero-dark dark"><p className="kicker">{eyebrow}</p><h1>{title}</h1></section>}
function Table({rows}:{rows:string[][]}){return <table className="price-table"><thead><tr><th>Service</th><th>What's included</th><th>Price</th></tr></thead><tbody>{rows.map(r=><tr key={r[0]}><td>{r[0]}</td><td>{r[1]}</td><td>{r[2]}</td></tr>)}</tbody></table>}
function Services(){return <><PageHero eyebrow="SERVICES · UPDATED MAY 2026" title="Everything Post@WEB does, in one place."/><section className="service-index section">{['Admin & Government','Courier & Logistics','Print, Photo & Stationery','The AI Help Desk'].map((g,i)=><div className="service-row" key={g}><h2>{g}</h2><p>{i===3?pillars.map(p=>p[2]).join(' · '):services.slice(i*4,i*4+6).join(' · ')}</p></div>)}<div className="common"><h2>Common requests</h2>{['Licence renewal Johannesburg','Passport photo near me','FedEx drop-off Rosebank','The Courier Guy Rosebank','AI headshots South Africa','Company profile design'].map(x=><a href="/contact" key={x}>{x}</a>)}</div></section></>}
function Ai(){return <><HeroDark eyebrow="THE AI HELP DESK" title="Eight categories. Eighty plus services. One counter."/><section className="ai-grid section">{pillars.map((p,i)=><article className={`ai-card style-${i}`} key={p[1]}><span>{p[0]}</span><h2>{p[2]}</h2><p>{p[3]}</p><strong>{i===0?'16 packs':p[4]}</strong><a href={`/ai-help-desk/${p[1]}`}>Open category →</a></article>)}</section><section className="operating section"><div><b>01</b><h3>Post@WEB sells.</h3><p>The counter hears the problem and collects the brief.</p></div><div><b>02</b><h3>Simora fulfils.</h3><p>The AI back-office turns it into a finished deliverable.</p></div><div><b>03</b><h3>Customer wins.</h3><p>Same-day progress and something usable in hand.</p></div></section></>}
function Photoshoot(){return <><section className="photo-hero"><img src={I.headshot} alt="Professional headshot"/><h1>AI Photoshoots. Walk-in studio prices.</h1></section><section className="photo-explain section"><div><p className="kicker">THE KILLER CATEGORY</p><p>Post@WEB already has the cameras, lighting, printers and counter workflow. The in-store session captures the customer honestly. The AI back-office creates the variations.</p></div><div className="stat"><strong>30s</strong><span>In-store photo session. Then AI does the rest.</span></div></section><section className="section"><Table rows={photoRows}/></section><section className="gallery-four"><img src={I.headshot}/><img src={I.family}/><img src={I.owner}/><img src={I.studio}/></section><section className="school-angle section"><p className="kicker">BULK & SCHOOL CONTRACTS</p><h2>R105,000 from one Saturday.</h2><p>Three hundred learners at R350 per pack creates a R105,000 school photo programme before the parents have left the hall.</p></section><section className="photo-cta"><img src={I.service}/><a href="/contact">Book your shoot →</a></section></>}
function Pillar(){return <><section className="pillar-hero"><div><p className="kicker">AI HELP DESK</p><h1>Walk in with a problem. Leave with the deliverable.</h1><p>Dense, practical AI service packs sold at the counter and fulfilled by the back-office.</p><a className="btn primary" href="/contact">Book this service →</a></div><img src={I.business}/></section><section className="section"><Table rows={photoRows.slice(0,6)}/></section><section className="pullquote"><span>“</span><blockquote>Most customers do not need software. They need the professional thing finished.</blockquote><cite>Post@WEB counter note</cite></section></>}
function Bundles(){return <><HeroDark eyebrow="BUNDLES" title="Don't buy services. Buy outcomes."/><section className="bundle-rows section">{bundles.map(b=><article key={b[0]}><img src={b[2]}/><div><h2>{b[0]}</h2><strong>{b[1]}</strong><p>{b[3]}</p><a href="/contact">Book this →</a></div></article>)}</section><BundlesTeaser/></>}
function ForBusiness(){return <><PageHero eyebrow="B2B & SCHOOLS" title="One Saturday. R105,000+ in revenue."/><section className="segments section">{['Schools','Churches','Sports','Mall Tenants'].map((h,i)=><article className={`seg-${i}`}><h2>{h}</h2><p>Packaged service days, print collateral and AI-backed fulfilment for organised groups.</p></article>)}</section><Form title="Book a B2B call →"/></>}
function Locations(){return <><PageHero eyebrow="STORE FINDER" title="Find your nearest Post@WEB."/><section className="map"><iframe title="map" src="https://www.google.com/maps?q=Rosebank%20Mall%20Johannesburg&output=embed"/></section><section className="store-list section">{['Post@WEB Rosebank','Post@WEB Dobsonville'].map(x=><article key={x}><h2>{x}</h2><p>Placeholder address to be confirmed · +27 XX XXX XXXX</p><em>Selected stores may not offer every AI service yet.</em><div><a href="https://maps.google.com">Google Maps →</a><a href="https://www.waze.com">Waze →</a></div></article>)}</section></>}
function Franchise(){return <><section className="franchise-hero dark"><h1>Run South Africa's most ambitious walk-in service brand.</h1><a className="btn primary" href="/contact">Download the franchise pack →</a></section><section className="stats section"><div><strong>R12k–R110k</strong><span>average monthly per store</span></div><div><strong>8</strong><span>service pillars</span></div><div><strong>80+</strong><span>services per store</span></div></section><Form title="Apply for a franchise →"/></>}
function About(){return <><section className="about-hero"><img src={I.location}/><div><h1>Post@WEB</h1><p>Founded by Alwyn van der Merwe, creator of Mochachos, and built around the trust of the mall counter.</p></div></section><section className="story section"><p><em>A mall is where South Africans already go when the admin has to get done.</em></p><p>Post@WEB turns that habit into a sharper retail service brand: licence renewals, courier, printing, photos, keys, checks and documents under one roof.</p></section></>}
function Contact(){return <><HeroDark eyebrow="CONTACT" title="Talk to us."/><Form title="Get a quote →"/></>}
function Form({title}:{title:string}){return <section className="form-section section"><h2>{title}</h2><form><input placeholder="Name"/><input placeholder="Organisation"/><select><option>Service needed</option></select><input placeholder="Contact number"/><textarea placeholder="Tell us what you need done"/><button type="button" className="btn primary">Send enquiry</button></form></section>}
function Footer(){return <footer className="footer"><div className="footer-grid"><div><a className="wordmark" href="/"><span>POST</span><b>@WEB</b></a><p>“Walk in with an idea, photo, document or business problem. Walk out with a professional AI-powered solution.”</p><div className="socials">IG · FB · LI</div></div><div><h3>Services</h3>{services.slice(0,12).map(s=><a href="/services" key={s}>{s}</a>)}</div><div><h3>AI Help Desk</h3>{pillars.map(p=><a href={`/ai-help-desk/${p[1]}`} key={p[1]}>{p[2]}</a>)}</div><div><h3>Locations</h3><a href="/locations">Rosebank</a><a href="/locations">Dobsonville / Soweto</a></div><div><h3>Company</h3>{['About','Franchise','Contact','Press','Privacy'].map(x=><a href={`/${x.toLowerCase()}`} key={x}>{x}</a>)}</div></div><div className="footer-base"><span>© Post@WEB 2026 · Site by Studio Name</span><span>The Courier Guy · FedEx · Kodak</span></div></footer>}
export default App
